package work.dao.model;

import com.jdframe.sys.core.model.T_vo;
import java.math.BigDecimal;

public class T_work_tidenKey implements T_vo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORK_TIDEN.LINENUMBER //remark is :null
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    private BigDecimal linenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORK_TIDEN.TPAYER //remark is :null
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    private String tpayer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WORK_TIDEN
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public T_work_tidenKey(BigDecimal linenumber, String tpayer) {
        this.linenumber = linenumber;
        this.tpayer = tpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WORK_TIDEN
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public T_work_tidenKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORK_TIDEN.LINENUMBER
     *
     * @return the value of T_WORK_TIDEN.LINENUMBER
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public BigDecimal getLinenumber() {
        return linenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORK_TIDEN.LINENUMBER
     *
     * @param linenumber the value for T_WORK_TIDEN.LINENUMBER
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public void setLinenumber(BigDecimal linenumber) {
        this.linenumber = linenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORK_TIDEN.TPAYER
     *
     * @return the value of T_WORK_TIDEN.TPAYER
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public String getTpayer() {
        return tpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORK_TIDEN.TPAYER
     *
     * @param tpayer the value for T_WORK_TIDEN.TPAYER
     *
     * @mbggenerated Wed Jan 08 17:05:34 CST 2014
     */
    public void setTpayer(String tpayer) {
        this.tpayer = tpayer == null ? null : tpayer.trim();
    }
}